// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';
import {api} from '../models';

export function CreateModel(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number,arg6:Array<string>):Promise<db.ModelSpec>;

export function DeleteModel(arg1:string):Promise<void>;

export function GetAPIURL():Promise<string>;

export function GetAppVersion():Promise<string>;

export function GetRoutingLog(arg1:string):Promise<api.RouteResult>;

export function IssueKey(arg1:string):Promise<api.IssueKeyResult>;

export function ListKeys():Promise<Array<db.AgentKey>>;

export function ListModels():Promise<Array<db.ModelSpec>>;

export function ListRoutingLogs():Promise<Array<db.RoutingLog>>;

export function Quit():Promise<void>;

export function RevokeKey(arg1:string):Promise<void>;

export function Route(arg1:string,arg2:string,arg3:Array<string>,arg4:string):Promise<api.RouteResult>;

export function SetModelEnabled(arg1:string,arg2:boolean):Promise<db.ModelSpec>;
