// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateModel(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['CreateModel'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function DeleteModel(arg1) {
  return window['go']['main']['App']['DeleteModel'](arg1);
}

export function GetAPIURL() {
  return window['go']['main']['App']['GetAPIURL']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetRoutingLog(arg1) {
  return window['go']['main']['App']['GetRoutingLog'](arg1);
}

export function IssueKey(arg1) {
  return window['go']['main']['App']['IssueKey'](arg1);
}

export function ListKeys() {
  return window['go']['main']['App']['ListKeys']();
}

export function ListModels() {
  return window['go']['main']['App']['ListModels']();
}

export function ListRoutingLogs() {
  return window['go']['main']['App']['ListRoutingLogs']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function RevokeKey(arg1) {
  return window['go']['main']['App']['RevokeKey'](arg1);
}

export function Route(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Route'](arg1, arg2, arg3, arg4);
}

export function SetModelEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetModelEnabled'](arg1, arg2);
}
